# Template cho developer sandbox
# developer_build workflow sẽ render file này để vô hiệu hoá Ingress (dùng NodePort)
services:
  storefront-bff:
    host: ""
  backoffice-bff:
    host: ""
  swagger-ui:
    host: ""
