# This is a template for sandbox environments.
# The GitHub Action developer_build will copy this file and modify the tags/ports.
services:
  storefront-ui:
    host: "" # No ingress for sandbox, rely on NodePort
  backoffice-ui:
    host: ""
  swagger-ui:
    host: ""
