registry: docker.io/ltchcmus
services:
  product:    { tag: main, port: 8080, nodePort: 30081 }
  cart:       { tag: main, port: 8080, nodePort: 30082 }
  order:      { tag: main, port: 8080, nodePort: 30083 }
  customer:   { tag: main, port: 8080, nodePort: 30084 }
  inventory:  { tag: main, port: 8080, nodePort: 30085 }
  tax:        { tag: main, port: 8080, nodePort: 30086 }
  media:      { tag: main, port: 8080, nodePort: 30087 }
  search:     { tag: main, port: 8080, nodePort: 30088 }
  storefront-bff:  { tag: main, port: 8080, nodePort: 30089 }
  storefront-ui:   { tag: main, port: 3000, nodePort: 30090, host: storefront.yas.lethanhcong.site }
  backoffice-bff:  { tag: main, port: 8080, nodePort: 30091 }
  backoffice-ui:   { tag: main, port: 3000, nodePort: 30092, host: backoffice.yas.lethanhcong.site }
  swagger-ui:      { tag: main, port: 8080, nodePort: 30093, host: swagger.yas.lethanhcong.site }
