{{- range $name, $svc := .Values.services }}
{{- if $svc.host }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: {{ $svc.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $svc.port }}
{{- end }}
{{- end }}
