{{/*
  Secrets for infrastructure credentials
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: yas-postgresql-credentials-secret
  labels:
    {{- include "yas.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRESQL_USERNAME: {{ .Values.global.postgresql.username | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.global.postgresql.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: yas-redis-credentials-secret
  labels:
    {{- include "yas.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.global.redis.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: yas-keycloak-credentials-secret
  labels:
    {{- include "yas.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_BACKOFFICE_BFF_CLIENT_SECRET: {{ .Values.global.keycloak.backofficeBffClientSecret | quote }}
  KEYCLOAK_STOREFRONT_BFF_CLIENT_SECRET: {{ .Values.global.keycloak.storefrontBffClientSecret | quote }}
  KEYCLOAK_CUSTOMER_MANAGEMENT_CLIENT_SECRET: {{ .Values.global.keycloak.customerManagementClientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: yas-elasticsearch-credentials-secret
  labels:
    {{- include "yas.labels" . | nindent 4 }}
type: Opaque
stringData:
  ELASTICSEARCH_USERNAME: {{ .Values.global.elasticsearch.username | quote }}
  ELASTICSEARCH_PASSWORD: {{ .Values.global.elasticsearch.password | quote }}
