# Dev inherits everything from base values.yaml
# We can just override the global domain here explicitly if needed.
global:
  domain: yas.lethanhcong.site
  serviceType: ClusterIP
services:
  storefront:
    tag: 637827f3799fec680e7fcf2ae8f999fc3206d1a6
  search:
    tag: 30a5304fda5b574aa291a181e04f9294d092209c
