global:
  domain: staging.yas.lethanhcong.site

services:
  storefront-bff:
    host: staging.storefront.yas.lethanhcong.site
  backoffice-bff:
    host: staging.backoffice.yas.lethanhcong.site
  swagger-ui:
    host: staging.swagger.yas.lethanhcong.site
