global:
  domain: staging.yas.lethanhcong.site
  serviceType: ClusterIP
services:
  storefront-bff:
    host: staging.storefront.yas.lethanhcong.site
    tag: v1.0.1
  backoffice-bff:
    host: staging.backoffice.yas.lethanhcong.site
    tag: v1.0.1
  swagger-ui:
    host: staging.swagger.yas.lethanhcong.site
  backoffice:
    tag: v1.0.1
  cart:
    tag: v1.0.1
  charts:
    tag: v1.0.1
  customer:
    tag: v1.0.1
  inventory:
    tag: v1.0.1
  location:
    tag: v1.0.1
  media:
    tag: v1.0.1
  order:
    tag: v1.0.1
  payment:
    tag: v1.0.1
  payment-paypal:
    tag: v1.0.1
  product:
    tag: v1.0.1
  promotion:
    tag: v1.0.1
  rating:
    tag: v1.0.1
  recommendation:
    tag: v1.0.1
  sampledata:
    tag: v1.0.1
  search:
    tag: v1.0.1
  storefront:
    tag: v1.0.1
  tax:
    tag: v1.0.1
  webhook:
    tag: v1.0.1
